server.port=8081

spring.application.name=api-gateway

spring.main.web-application-type=reactive

spring.cloud.gateway.server.webflux.routes[0].id=loan-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://loanservice:8092
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/loan/**
server.webflux.routes[0].id=account-service  
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080  
server.webflux.routes[0].predicates[0]=Path=/api/v1/accountdetails,/api/v1/accountdetails/**

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.cloud.gateway.route=TRACE
logging.level.reactor.netty.http.client=DEBUG
